version: "3"

services:
  nginx:
    restart: unless-stopped
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.7.4
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
      - nginx
      - slack

  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: btcpayserver/letsencrypt-nginx-proxy-companion:1.10.0
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-v01.api.letsencrypt.org/directory}
    links:
      - nginx-gen
      - mattermost_app
  slack:
    image: nicolasdorier/slack-invite-automation:latest
    container_name: slack
    command: "node ./bin/www"
    environment:
      SLACK_URL: ${SLACK_URL:-forkbitpay.slack.com}
      PORT: 80
      COMMUNITY_NAME: "BTCPay Server"
      SLACK_TOKEN: ${SLACK_TOKEN}
      VIRTUAL_HOST: ${SLACK_HOST}
      SSL_POLICY: "Mozilla-Modern"
      VIRTUAL_PORT: "80"
      VIRTUAL_NETWORK: "nginx-proxy"
      LETSENCRYPT_HOST: ${SLACK_HOST}
      LETSENCRYPT_EMAIL: "<no value>"
    expose:
      - 80
  mattermost_db:
    image: mattermost/mattermost-prod-db:5.7.0 
    volumes:
      - mm-dbdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    restart: unless-stopped
    expose:
      - 5432
    links:
        - mattermost_app
  mattermost_app:
    restart: unless-stopped
    image: mattermost/mattermost-prod-app:5.7.0
    volumes:
      - mm-config:/mattermost/config:rw
      - mm-data:/mattermost/data:rw
      - mm-logs:/mattermost/logs:rw
      - mm-plugins:/mattermost/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # use service's hostname
      DB_HOST: "mattermost_db"
      DB_PORT_NUMBER: 5432
      MM_USERNAME: "mmuser"
      MM_PASSWORD: "mmuser_password"
      MM_DBNAME: "mattermost"
      VIRTUAL_PORT: "8000"
      VIRTUAL_HOST: ${MATTERMOST_HOST}
      VIRTUAL_NETWORK: "nginx-proxy"
      LETSENCRYPT_HOST: ${MATTERMOST_HOST}
      LETSENCRYPT_EMAIL: "<no value>"
      EDITION: "team"
  mattermost_bridge:
    restart: unless-stopped
    image: 42wim/matterbridge:1.12.3
    volumes:
      - ./matterbridge.toml:/matterbridge.toml
        
volumes:
    nginx_conf:
    nginx_vhost:
    nginx_html:
    nginx_certs:
    mm-dbdata:
    mm-config:
    mm-data:
    mm-logs:
    mm-plugins: