[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="btcpay_bot"

[mattermost]
    [mattermost.btcpay]
    Server="chat.nbitstack.com"
    Team="btcpay"
    Login="kukks"
    Password="bukkake"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[slack]
	[slack.forkbitpay]
	Token="xoxb-123456789-aBeautifulBotToken"
	RemoteNickFormat="{BRIDGE} - @{NICK}"	

[telegram]
	[telegram.btcpay]
	#See https://core.telegram.org/bots#6-botfather 
	#and https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau
	Token="Yourtokenhere"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "	
	
[gitter.nbitcoin]
#You can get your token by going to https://developer.gitter.im/docs/welcome and SIGN IN
	Token="Yourtokenhere"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "